// <auto-generated />
using System;
using GestionEDT_Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionEDT_Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507203210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.EDT", b =>
                {
                    b.Property<int>("IdEDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEDT"));

                    b.Property<string>("CodeSalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("integer");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer");

                    b.HasKey("IdEDT");

                    b.HasIndex("CodeSalle");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdMatiere");

                    b.ToTable("EDTs");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEnseignant"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomEnseignant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEnseignant");

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Enseigner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("integer");

                    b.Property<int>("IdProm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdProm");

                    b.ToTable("Enseigners");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("integer");

                    b.Property<string>("NomMatiere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMatiere");

                    b.HasIndex("IdEnseignant");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Promotion", b =>
                {
                    b.Property<int>("IdProm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProm"));

                    b.Property<string>("CodeSalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mention")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomProm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProm");

                    b.HasIndex("CodeSalle");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Salle", b =>
                {
                    b.Property<string>("CodeSalle")
                        .HasColumnType("text");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<string>("NomBatiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodeSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.EDT", b =>
                {
                    b.HasOne("GestionEDT_Core.Models.Entities.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("CodeSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEDT_Core.Models.Entities.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEDT_Core.Models.Entities.Matiere", "Matiere")
                        .WithMany()
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Matiere");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Enseigner", b =>
                {
                    b.HasOne("GestionEDT_Core.Models.Entities.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEDT_Core.Models.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("IdProm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Matiere", b =>
                {
                    b.HasOne("GestionEDT_Core.Models.Entities.Enseignant", "Enseignant")
                        .WithMany()
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("GestionEDT_Core.Models.Entities.Promotion", b =>
                {
                    b.HasOne("GestionEDT_Core.Models.Entities.Salle", "Salle")
                        .WithMany()
                        .HasForeignKey("CodeSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salle");
                });
#pragma warning restore 612, 618
        }
    }
}
